language: node_js
node_js:
  - 11.2.0
cache: npm
script: gatsby build
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: "openboise-www"
  skip_cleanup: true
  acl: public_read
  local_dir: public
