language: node_js
node_js:
  - 11.2.0
cache: npm
script: gatsby build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "openboise-www"
  skip_cleanup: true
  on:
    branch: master
